### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Lotus6** [CipherKill/windows-login-phish#1]
Can I give the browser F11 full screen when running

**Comment by ReptilianPride** [comment]
Yes you can

**Comment by Lotus6** [comment]
JS code can achieve F11 full screen？

**Comment by ReptilianPride** [comment]
> JS code can achieve F11 full screen？

F11 is just a browser shortcut for full screen and is independent of the program itself.

Modern browsers don't allow auto full screen for security reasons. As in, only through user gestures we can make full screen with JS. But I am trying to find a workaround for this.

**Comment by Lotus6** [comment]
Thank you for your reply and hope to see your update.
